### PR TITLE
Get modules list without su

### PR DESCRIPTION
**Pull request by DVDAndroid**

### CODE REVIEW

**Comment by ethernet8023** [comment]
This approach doesn't work as of right now. Trying to read the Xposed modules.list file from another app's context (in this case, settings) will cause a java.lang.RuntimeException: java.io.FileNotFoundException: /data/data/de.robv.android.xposed.installer/conf/modules.list: open failed: EACCES (Permission denied).

I'm currently looking for an app context that can be hooked to let us read that file.
Hooking the Xposed installer does work, but we'd need a way to force the Xposed installer package to be loaded. I'd rather avoid a hack like that, though, and hook a context that has read access to the file.

**Comment by DVDAndroid** [comment]
Strange.. Tested and working on my Nexus 5, Xposed v79,.
screenshot_20151229-170715

Edit: tested on the same device, but with Cyanogenmod. Result: not working

**Comment by ethernet8023** [comment]
Very strange. I was on Xposed v78, but flashing v79 seems to have made no change for me. I've disabled all my other modules, and compiled & ran your code on my Nexus 5, Android 6.0.1, Xposed v79, and I still get the EACCES error. Would you be so kind as to provide an APK that works for you? I'll see if there's any difference between our compiled code.

**Comment by DVDAndroid** [comment]
APK: http://goo.gl/1Mpla2
However, I tested it on Cyanogenmod, same device, same Xposed Version, but it doesn't work.

(if it could be useful) In either roms I use a modified version of Xposed Installer, but it makes no differences.

**Comment by ethernet8023** [comment]
Your APK doesn't work on my device either. I've downloaded your version of the Xposed installer, but it doesn't seem to make any difference. Very strange..

**Comment by DVDAndroid** [comment]
I've downloaded and installed official Xposed Installer 3.0 alpha4 (non-modified). It works, always on my primay ROM (Nexus 5, 6.0.1, Xposed v79).

On both ROMs, permission to modules.list file is rw-rw-r--

**Comment by ethernet8023** [comment]
I have no idea what could possibly be making a difference here. My modules.list file is also -rw-rw-r--. I'm going to wipe my device and try from stock.

**Comment by DVDAndroid** [comment]
I don't think that a wipe can solve the problem. My Cyanogenmod ROM is untouched and clean, added only Xposed, and there doesn't work

**Comment by ethernet8023** [comment]
CyanogenMod apparently has their own settings provider that's incompatible - I'm more interested in fixing the root problem on stock Android before anything else.

**Pull request closed without merging**
